### PR TITLE
Fix typing error in `FetchArticles.tsx`

### LINKED ISSUE #56: Fix Typing Issue in FetchArticles file
The build is currently failing due to typing issues in `FetchArticles.tsx`.

### PR DESCRIPTION
**Pull request by Green-Ranger11**
This closes #56

### CODE REVIEW

**Comment by Green-Ranger11** [comment]
image

File: src/components/FetchArticles.tsx [hunk 1]
```diff
@@ -24,10 +24,13 @@ const FetchArticles: FunctionComponent<Props> = ({ articleType }) => {
 
   useEffect(() => {
     const loadArticles = async () => {
-      const data = await getArticles(startEntries, articleType).catch((err) => {
-        console.log(err)
-        setError(err)
-      })
```
Comment (Green-Ranger11) [inline src/components/FetchArticles.tsx:30]: @JasonFritsche there was a catch on the await (which is strange - hence why the nullable) so I just removed that and added a check if the return from the `articlesApi` is an error or not.

File: src/components/FetchArticles.tsx [hunk 2]
```diff
@@ -24,10 +24,13 @@ const FetchArticles: FunctionComponent<Props> = ({ articleType }) => {
...
+      const data = await getArticles(startEntries, articleType)
+
+      if (data.error) {
+        console.log(data.error)
+        setError(data.error)
+      }
+
```
Comment (Green-Ranger11) [inline src/components/FetchArticles.tsx:33]: @JasonFritsche there was a catch on the await (which is strange - hence why the nullable) so I just removed that and added a check if the return from the articlesApi is an error or not.

**Comment by Green-Ranger11** [comment]
@JasonFritsche pinging just in case
